-- EMR Module: patient_problems table
-- UUID primary key generated by Hibernate (GenerationType.UUID).
-- No FK constraint on patient_id — audit pattern (records survive patient purge).

CREATE TABLE patient_problems (
    id          UUID            NOT NULL,
    patient_id  VARCHAR(14)     NOT NULL,
    title       VARCHAR(200)    NOT NULL,
    description TEXT,
    icd_code    VARCHAR(20),
    severity    VARCHAR(20)     NOT NULL,
    status      VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    onset_date  DATE,
    notes       TEXT,
    created_by  VARCHAR(100)    NOT NULL,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_by  VARCHAR(100),
    updated_at  TIMESTAMPTZ,

    CONSTRAINT pk_patient_problems PRIMARY KEY (id)
);

CREATE INDEX idx_patient_problems_patient_id ON patient_problems (patient_id, status);
