-- EMR Module: patient_medications table
-- UUID primary key generated by Hibernate (GenerationType.UUID).
-- prescribed_by is always set from auth context; never user-supplied.

CREATE TABLE patient_medications (
    id              UUID            NOT NULL,
    patient_id      VARCHAR(14)     NOT NULL,
    medication_name VARCHAR(200)    NOT NULL,
    generic_name    VARCHAR(200),
    dosage          VARCHAR(100)    NOT NULL,
    frequency       VARCHAR(100)    NOT NULL,
    route           VARCHAR(20)     NOT NULL,
    start_date      DATE            NOT NULL,
    end_date        DATE,
    indication      TEXT,
    prescribed_by   VARCHAR(100)    NOT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    notes           TEXT,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,

    CONSTRAINT pk_patient_medications PRIMARY KEY (id)
);

CREATE INDEX idx_patient_medications_patient_id ON patient_medications (patient_id, status);
