openapi: "3.0.3"
info:
  title: EMR Medication List API
  version: "1.0"
  description: Patient medication list management (US3)

paths:
  /api/v1/patients/{patientId}/medications:
    post:
      summary: Prescribe a medication
      description: |
        Creates a new medication record. `prescribedBy` is auto-populated from the
        authenticated user's identity — any value supplied in the request body is ignored.
      operationId: prescribeMedication
      tags: [Medications]
      security:
        - bearerAuth: []
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: string
            example: "P2026001"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrescribeMedicationRequest'
            example:
              medicationName: "Metformin"
              dosage: "500mg"
              frequency: "twice daily"
              route: "ORAL"
              startDate: "2026-02-20"
      responses:
        "201":
          description: Medication prescribed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicationResponse'
        "400":
          description: Validation error (missing required field, endDate before startDate)
        "401":
          description: Unauthenticated
        "403":
          description: Role not permitted (NURSE or RECEPTIONIST denied)
        "404":
          description: Patient not found

    get:
      summary: List a patient's medications
      description: Defaults to ACTIVE only. Use ?status=ALL for full history.
      operationId: listMedications
      tags: [Medications]
      security:
        - bearerAuth: []
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum: [ACTIVE, DISCONTINUED, COMPLETED, ALL]
            default: ACTIVE
      responses:
        "200":
          description: Medication list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MedicationResponse'
        "403":
          description: Role not permitted (RECEPTIONIST denied)
        "404":
          description: Patient not found

  /api/v1/patients/{patientId}/medications/{medicationId}:
    patch:
      summary: Update or discontinue a medication
      operationId: updateMedication
      tags: [Medications]
      security:
        - bearerAuth: []
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: string
        - name: medicationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMedicationRequest'
            example:
              status: "DISCONTINUED"
              endDate: "2026-02-20"
      responses:
        "200":
          description: Medication updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicationResponse'
        "400":
          description: Validation error
        "403":
          description: Role not permitted (NURSE or RECEPTIONIST denied)
        "404":
          description: Patient or medication not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PrescribeMedicationRequest:
      type: object
      required: [medicationName, dosage, frequency, route, startDate]
      properties:
        medicationName:
          type: string
          maxLength: 200
        genericName:
          type: string
          maxLength: 200
          nullable: true
        dosage:
          type: string
          maxLength: 100
        frequency:
          type: string
          maxLength: 100
        route:
          type: string
          enum: [ORAL, IV, IM, TOPICAL, INHALED, OTHER]
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
          nullable: true
          description: Must be ≥ startDate when provided
        indication:
          type: string
          nullable: true
        notes:
          type: string
          nullable: true

    UpdateMedicationRequest:
      type: object
      description: All fields optional — only provided fields are updated.
      properties:
        status:
          type: string
          enum: [ACTIVE, DISCONTINUED, COMPLETED]
          nullable: true
        endDate:
          type: string
          format: date
          nullable: true
        indication:
          type: string
          nullable: true
        notes:
          type: string
          nullable: true

    MedicationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        patientId:
          type: string
        medicationName:
          type: string
        genericName:
          type: string
          nullable: true
        dosage:
          type: string
        frequency:
          type: string
        route:
          type: string
          enum: [ORAL, IV, IM, TOPICAL, INHALED, OTHER]
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
          nullable: true
        indication:
          type: string
          nullable: true
        prescribedBy:
          type: string
        status:
          type: string
          enum: [ACTIVE, DISCONTINUED, COMPLETED]
        notes:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
          nullable: true
